package com.github.joshuataylor.datamancer.dbtcore.manifest

import com.github.joshuataylor.datamancer.core.services.DatamancerDbtProjectIndexService
import com.intellij.openapi.components.Service
import com.intellij.openapi.diagnostic.logger
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.vfs.VirtualFile
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.serialization.json.Json
import java.util.concurrent.ConcurrentHashMap

/**
 * Service that loads and caches dbt manifest.json files for each dbt project root.
 *
 * The manifest is generated by dbt after any `dbt parse`, `dbt compile`, or `dbt run`.
 * It contains compiled SQL, column metadata with data types, lineage graphs, and source
 * definitions that are not available from YAML schema files alone.
 *
 * Call [start] to perform the initial scan. The [DatamancerManifestFileListener] handles
 * incremental reloads when manifest files change on disk.
 */
@Service(Service.Level.PROJECT)
class DatamancerManifestService(private val project: Project, private val cs: CoroutineScope) {
    private val log = logger<DatamancerManifestService>()

    private val manifests = ConcurrentHashMap<String, DbtManifest>()

    private val json = Json {
        ignoreUnknownKeys = true
        isLenient = true
    }

    /**
     * Perform the initial scan of all known dbt project roots for manifest.json files.
     * Should be called after smart mode is ready and the index service has been populated.
     */
    fun start() {
        log.debug("Starting manifest service for project: ${project.name}")
        cs.launch(Dispatchers.IO) {
            val indexService = DatamancerDbtProjectIndexService.getInstance(project)
            val configs = indexService.getAllDbtConfigsSync()
            log.debug("Scanning ${configs.size} dbt project root(s) for manifest.json")
            for (config in configs.values) {
                val projectRoot = config.projectRoot
                reloadManifest(projectRoot)
            }
        }
    }

    /**
     * Reload the manifest for a given project root. Called on startup and by the file watcher.
     */
    fun reloadManifest(projectRoot: String) {
        val manifestPath = "$projectRoot/target/manifest.json"
        val file = LocalFileSystem.getInstance().findFileByPath(manifestPath)
            ?: LocalFileSystem.getInstance().refreshAndFindFileByPath(manifestPath)

        if (file == null || !file.exists()) {
            log.debug("No manifest.json found at: $manifestPath")
            return
        }

        val manifest = loadManifest(file)
        if (manifest != null) {
            manifests[projectRoot] = manifest
            log.debug("Loaded manifest for project $projectRoot: ${manifest.nodes.size} nodes, ${manifest.sources.size} sources")
        }
    }

    private fun loadManifest(manifestFile: VirtualFile): DbtManifest? {
        return runCatching {
            val content = manifestFile.inputStream.bufferedReader().readText()
            json.decodeFromString<DbtManifest>(content)
        }.onFailure { log.warn("Failed to parse manifest.json at ${manifestFile.path}", it) }.getOrNull()
    }

    fun getManifest(projectRoot: String): DbtManifest? = manifests[projectRoot]

    fun getAllManifests(): Map<String, DbtManifest> = manifests

    /**
     * Find a model/seed/snapshot node by name across all manifests, or within a specific project root.
     */
    fun getNode(projectRoot: String, modelName: String): DbtManifestNode? {
        val manifest = manifests[projectRoot] ?: return null
        return manifest.nodes.values.firstOrNull {
            it.name == modelName && it.resourceType in listOf("model", "seed", "snapshot")
        }
    }

    fun getSource(projectRoot: String, sourceName: String, tableName: String): DbtManifestSource? {
        val manifest = manifests[projectRoot] ?: return null
        return manifest.sources.values.firstOrNull {
            it.sourceName == sourceName && it.name == tableName
        }
    }

    fun getCompiledSql(projectRoot: String, modelName: String): String? =
        getNode(projectRoot, modelName)?.compiledCode

    /**
     * Returns the child_map entries for the given unique_id (nodes that depend on this node).
     */
    fun getLineageDependencies(projectRoot: String, uniqueId: String): List<String> =
        manifests[projectRoot]?.childMap?.get(uniqueId) ?: emptyList()

    /**
     * Returns the parent_map entries for the given unique_id (nodes this node depends on).
     */
    fun getLineageDependents(projectRoot: String, uniqueId: String): List<String> =
        manifests[projectRoot]?.parentMap?.get(uniqueId) ?: emptyList()

    /**
     * Find column metadata from the manifest for a given model and column name, searching
     * across all cached project roots.
     */
    fun findColumnMetadata(modelName: String, columnName: String): DbtManifestColumn? {
        for ((projectRoot, _) in manifests) {
            val node = getNode(projectRoot, modelName) ?: continue
            val col = node.columns.values.firstOrNull { it.name.equals(columnName, ignoreCase = true) }
            if (col != null) return col
        }
        return null
    }

    /**
     * Find the compiled SQL for a model, searching across all cached project roots.
     */
    fun findCompiledSql(modelName: String): String? {
        for ((projectRoot, _) in manifests) {
            val sql = getCompiledSql(projectRoot, modelName)
            if (!sql.isNullOrBlank()) return sql
        }
        return null
    }

    companion object {
        fun getInstance(project: Project): DatamancerManifestService =
            project.getService(DatamancerManifestService::class.java)
    }
}
